import = [
    "~/.config/alacritty/themes/themes/ayu_mod.toml"
]

[font]
size=11.5
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular"  }

[window]
padding = { x = 6, y = 6 }
opacity = 0.95

[cursor]
style = { shape = "beam", blinking = "on" }

